name: Build and publish package
on:
  release:
    types: [published]

jobs:
  build-and-publish:
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/k8r
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Publish distribution 📦 to PyPI
        run: uv publish
